[general]
import = [
  "~/git/dotfiles/alacritty/.config/alacritty/themes/ayu_dark.toml"
]

[window]
padding = { x = 35, y = 15 }
dimensions = { columns = 120, lines = 30 }
dynamic_padding = true
title = "Alacritty"
decorations = "None"
blur = true
opacity = 1.0
startup_mode = "Maximized"

[font]
size = 14
[font.normal]
family = "ZedMono Nerd Font"
style = "Regular"

[cursor]
[cursor.style]
shape = "Underline"
blinking = "On"

[mouse]
hide_when_typing = true
