# AUTO-GENERATED by generate-colors.sh - do not edit manually
# Source: nuxt.json

cl_default="#0E1D31"
cl_border="#1E3A5F"
cl_inactive="#94A3B8"
cl_active="#FFC600"
cl_accent="#00C16A"
cl_bright_white="#FFFFFF"
