# Colors (Goldovsky)

# Default colors
[colors.primary]
background = '#181B20'
foreground = '#F2F0EF'

# Normal colors
[colors.normal]
black   = '#4C4C4C'
red     = '#fb4934'
green   = '#A9B665'
yellow  = '#EFBF04'
blue    = '#6B9EA0'
magenta = '#C07AAF'
cyan    = '#7BA88D'
white   = '#F2F0EF'

# Bright colors
[colors.bright]
black   = '#6E6E6E'
red     = '#FC6A5D'
green   = '#C2CA6C'
yellow  = '#F5D76E'
blue    = '#89BFC1'
magenta = '#D49AC5'
cyan    = '#A1CFAE'
white   = '#FFFFFF'
