# Colors (Material Theme)

# Default colors
[colors.primary]
# background = '#353839' # Onyx
# background = '#00674F' # vert emeraude
background = '#1e282d' # dark blue
foreground = '#F2F0EF'

# Normal colors
[colors.normal]
black   = '#666666'
red     = '#fb4934' # Good red
green   = '#c3e88d'
# green   = '#636B2F' # olive-green
yellow  = '#EFBF04' # gold-yellow
blue    = '#80cbc4'
magenta = '#ff2f90'
cyan    = '#aeddff'
white   = '#F2F0EF'

# Bright colors
[colors.bright]
black   = '#ff262b'
red     = '#eb606b'
green   = '#c3e88d'
yellow  = '#f7eb95'
blue    = '#7dc6bf'
magenta = '#6c71c4'
cyan    = '#35434d'
white   = '#F2F0EF'
