#!/bin/bash
# generate-colors.sh - Generate tool-specific color configs from JSON source

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
MAGENTA='\033[0;35m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PRESETS_DIR="${SCRIPT_DIR}/presets"
OUTDIR="${SCRIPT_DIR}/outputs"
STARSHIP_CONFIG="${HOME}/git/dotfiles/starship/.config/starship/starship.toml"

usage() {
    echo -e "${BOLD}Usage:${NC} $(basename "$0") [theme-name]"
    echo ""
    echo "Generate color configs for alacritty, tmux, and starship from a JSON theme file."
    echo ""
    echo -e "${BOLD}Arguments:${NC}"
    echo "  theme-name    Name of the JSON file (without .json extension)"
    echo "                Defaults to 'goldovsky' if not specified"
    echo ""
    echo -e "${BOLD}Examples:${NC}"
    echo "  $(basename "$0")              # Use goldovsky.json"
    echo "  $(basename "$0") cobalt       # Use cobalt.json"
    echo "  $(basename "$0") --help       # Show this help"
    echo ""
    echo -e "${BOLD}Available themes:${NC}"
    ls "$PRESETS_DIR"/*.json 2>/dev/null | xargs -I {} basename {} .json || echo "  (none found)"
}

# Handle help flag
if [[ "$1" == "--help" ]] || [[ "$1" == "-h" ]]; then
    usage
    exit 0
fi

THEME="${1:-goldovsky}"
SOURCE="${PRESETS_DIR}/${THEME}.json"

# Check if source file exists
if [ ! -f "$SOURCE" ]; then
    echo -e "${RED}Error:${NC} Theme file not found: ${SOURCE}"
    echo ""
    echo -e "${YELLOW}Available themes:${NC}"
    ls "$PRESETS_DIR"/*.json 2>/dev/null | xargs -I {} basename {} .json || echo "  (none found)"
    exit 1
fi

# Check if python3 is available
if ! command -v python3 &> /dev/null; then
    echo -e "${RED}Error:${NC} python3 is required for JSON parsing"
    exit 1
fi

# Helper function to extract color from JSON
c() {
    python3 -c "import json; d=json.load(open('$SOURCE')); print(d['colors']['$1'])"
}

# Get theme name from JSON
THEME_NAME=$(python3 -c "import json; d=json.load(open('$SOURCE')); print(d['name'])")

echo -e "${BOLD}${CYAN}  󰏗 Generating colors for: ${THEME_NAME}${NC}"
echo -e "  ${BLUE}Source:${NC} ${THEME}.json"
echo ""

# --- Alacritty ---
cat > "${OUTDIR}/alacritty-theme.toml" << EOF
# AUTO-GENERATED by generate-colors.sh - do not edit manually
# Source: ${THEME}.json
[colors.primary]
background = '$(c background)'
foreground = '$(c foreground)'

[colors.normal]
black   = '$(c black)'
red     = '$(c red)'
green   = '$(c green)'
yellow  = '$(c yellow)'
blue    = '$(c blue)'
magenta = '$(c magenta)'
cyan    = '$(c cyan)'
white   = '$(c white)'

[colors.bright]
black   = '$(c bright-black)'
red     = '$(c bright-red)'
green   = '$(c bright-green)'
yellow  = '$(c bright-yellow)'
blue    = '$(c bright-blue)'
magenta = '$(c bright-magenta)'
cyan    = '$(c bright-cyan)'
white   = '$(c bright-white)'
EOF

echo -e "  ${GREEN}✓${NC} Alacritty  → ${OUTDIR}/alacritty-theme.toml"

# --- Tmux ---
cat > "${OUTDIR}/tmux-colors.tmux" << EOF
# AUTO-GENERATED by generate-colors.sh - do not edit manually
# Source: ${THEME}.json

# Background - match alacritty
set -g status-bg '$(c background)'

# Status right: session name (cyan)
set -g status-right '#[fg=$(c cyan),bold] #S#[nobold]  '

# Inactive windows (white for contrast on dark bg)
set -g window-status-format '#[fg=$(c white)]#I #W'

# Active window (gold accent, bold)
set -g window-status-current-format '#[fg=$(c gold-yellow),bold]#I #[fg=$(c gold-yellow),bold]#W'

# Pane borders
set -g pane-border-style 'fg=$(c background)'
set -g pane-active-border-style 'fg=$(c cyan)'

# Message styling
set -g message-style 'fg=$(c foreground),bg=$(c background)'
set -g message-command-style 'fg=$(c foreground),bg=$(c background)'
EOF

echo -e "  ${GREEN}✓${NC} Tmux       → ${OUTDIR}/tmux-colors.tmux"

# --- Starship (patch existing config) ---
if [ -f "$STARSHIP_CONFIG" ]; then
    # Generate palette content to temp file
    PALETTE_FILE=$(mktemp)
    cat > "$PALETTE_FILE" << EOF
[palettes.${THEME_NAME}]
# Cells: background / mid / foreground
dark-cell   = '$(c dark-cell)'
medium-cell = '$(c medium-cell)'
light-cell  = '$(c light-cell)'
# Neutrals
black       = '$(c black)'
light-black = '$(c bright-black)'
dark-grey   = '$(c dark-cell)'
grey        = '$(c medium-cell)'
light-grey  = '$(c light-cell)'
white       = '$(c white)'
# Semantic colors
red    = '$(c red)'
green  = '$(c green)'
blue   = '$(c blue)'
yellow = '$(c yellow)'
orange = '$(c bright-red)'
purple = '$(c magenta)'
cyan   = '$(c cyan)'
# Accent colors
olive-green = '$(c olive-green)'
gold-yellow = '$(c gold-yellow)'
EOF

    # Create temp file with updated starship config
    python3 << PYEOF
import re

with open("${STARSHIP_CONFIG}", "r") as f:
    content = f.read()

with open("${PALETTE_FILE}", "r") as f:
    palette_content = f.read()

# Pattern to match the palette section
pattern = r'# ---+\n# AUTO-GENERATED by generate-colors\.sh.*?(?=\n# ---+|\Z)'
replacement = "# ------------------------------------#\n# AUTO-GENERATED by generate-colors.sh - do not edit manually\n# Source: ${THEME}.json\n\n" + palette_content

new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

# If no auto-generated section exists, append it
if "AUTO-GENERATED by generate-colors.sh" not in content:
    new_content = content.rstrip() + "\n\n# ------------------------------------#\n# AUTO-GENERATED by generate-colors.sh - do not edit manually\n# Source: ${THEME}.json\n\n" + palette_content + "\n"

with open("${STARSHIP_CONFIG}", "w") as f:
    f.write(new_content)
PYEOF

    rm -f "$PALETTE_FILE"
    
    # Update palette reference
    sed -i "s/^palette = .*/palette = \"${THEME_NAME}\"/" "$STARSHIP_CONFIG"
    
    echo -e "  ${GREEN}✓${NC} Starship    → ${STARSHIP_CONFIG}"
else
    echo -e "  ${YELLOW}⚠${NC} Starship    → config not found at ${STARSHIP_CONFIG}"
fi

echo ""
echo -e "${BOLD}${MAGENTA}  󰏗 Theme: ${THEME_NAME}${NC}"
echo ""
echo -e "  ${CYAN}󰒩 Alacritty${NC}  → auto-reload"
echo -e "  ${CYAN}󰒭 Tmux${NC}      → tmux source-file ~/.tmux.conf"
echo -e "  ${CYAN}󰒮 Starship${NC}   → restart shell"
